export const START_FETCHING_FILE_METADATA = "START_FETCHING_FILE_METADATA";
export const FETCHING_FILE_METADATA_FAILED = "FETCHING_FILE_METADATA_FAILED";
export const FETCHING_FILE_METADATA_SUCCESS = "FETCHING_FILE_METADATA_SUCCESS";

export const START_FETCHING_FILE_DOWNLOAD_URL = "START_FETCHING_FILE_DOWNLOAD_URL";
export const FETCHING_FILE_DOWNLOAD_URL_FAILED = "FETCHING_FILE_DOWNLOAD_URL_FAILED";
export const FETCHING_FILE_DOWNLOAD_URL_SUCCESS = "FETCHING_FILE_DOWNLOAD_URL_SUCCESS";

// Constants
export const IS_NOT_INITIATED = "IS_NOT_INITIATED";
export const IS_LOADING = "IS_LOADING";
export const IS_SUCCESS = "IS_SUCCESS";
export const IS_FAILED = "IS_FAILED";

// Notifications
export const START_FETCHING_NOTIFICATIONS = "START_FETCHING_NOTIFICATIONS";
export const FETCHING_NOTIFICATIONS_SUCCESS = "FETCHING_NOTIFICATIONS_SUCCESS";
export const FETCHING_NOTIFICATIONS_STATUS = "FETCHING_NOTIFICATIONS_STATUS";

// Profile
export const START_PROFILE_FETCH = "START_PROFILE_FETCH";
export const PROFILE_FETCH_SUCCESS = "PROFILE_FETCH_SUCCESS";
export const PROFILE_FETCH_FAILED = "PROFILE_FETCH_FAILED";
