export const START_FETCHING_FILE_METADATA = "START_FETCHING_FILE_METADATA";
export const FETCHING_FILE_METADATA_FAILED = "FETCHING_FILE_METADATA_FAILED";
export const FETCHING_FILE_METADATA_SUCCESS = "FETCHING_FILE_METADATA_SUCCESS";
